---
title: "More Futzing with JSON lists"
output: html_notebook
---

## Load Packages
```{r}
library(tidyverse)
library(jsonlite)
library(repurrrsive)
```

## Load Data

https://scholars.duke.edu/widgets/api/v0.9/people/complete/all.json?uri=https://scholars.duke.edu/individual/per5862252

```{r}
sad_person <- fromJSON("https://scholars.duke.edu/widgets/api/v0.9/people/complete/all.json?uri=https://scholars.duke.edu/individual/per5862252")
```

## RStudio Helpers

```{r}
View(sad_person[["publications"]])

sad_person[["publications"]]
```





## Pick Up Here

```{r}
sad_person$positions %>% 
  purrr::flatten()

sad_person %>% 
  purrr::flatten()

#jsonlite::flatten(super_small)
```

```{r}
names(sad_person[[8]])
names(sad_person[[6]])
```

```{r}
sad_person[[6]]
```

```{r}
sad_person[["title"]]
sad_person[["label"]] 
sad_person[["publications"]]
```


```{r}
purrr::flatten(sad_person)
map(sad_person, "uri")
```


```{r}
map(sad_person, "label")
```


```{r}
sad_person[[4]]
```


```{r}
map_chr(sad_person[["label"]], 1)
map_chr(sad_person[["title"]], 1)
sad_person[["title"]]
map_chr(sad_person[["vivoType"]], 1)
map_chr(sad_person[["uri"]], 1)
#map(sad_person, 6)
sad_person[["publications"]] 
sad_person[["awards"]] 
sad_person[["awards"]][["attributes"]]

#(award_labels <- map_chr(sad_person[["awards"]]$label, 1))
as.list(sad_person$awards$label)

```


```{}
## list-columns = lists in a data frame ----
gt <- tibble(
  name = map_chr(got_chars, "name"),
  houses = map(got_chars, "allegiances")
)
View(gt)
```




```{r}
person_awards_df <- tibble(
  name = sad_person$label,
  title = sad_person$title,
  #awards = as.list(sad_person$awards$label)
  #awards = map(sad_person$awards$label, 1)
  awards = sad_person$awards$label
)

# tibble is similar to as.data.frame

#person_awards_df$awards[3]
person_awards_df
```



```{r}
map(sad_person$awards, 2)

sad_person$awards$label
```

